# -*- coding: utf-8 -*-
"""Copia de Tesis Alexis VF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VTWo03bjCNqeNFeaj7cuhN5AH4edqf9l
"""

# !pip install -q scikit-learn pandas numpy matplotlib ipywidgets

try:
    from kneed import KneeLocator
except ImportError:
    !pip -q install kneed
    from kneed import KneeLocator

import io
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from scipy import stats
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import PowerTransformer
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from IPython.display import display, HTML
from sklearn.cluster import DBSCAN
from sklearn.neighbors import NearestNeighbors

import warnings

warnings.filterwarnings("ignore", category=RuntimeWarning)

from google.colab import files  # para subir CSV (opción A)
# from google.colab import drive  # para Drive (opción B)

plt.style.use('ggplot')  # solicitado
FIGSIZE = (8, 6)         # mismo tamaño en todos los charts
SEED = 42

pd.set_option("display.max_columns", 200)
pd.set_option("display.width", 120)

upload = files.upload()         # selecciona tu .csv
fname = list(upload.keys())[0]
df = pd.read_csv(io.BytesIO(upload[fname]))
df.head()

assert 'Pais' in df.columns, "Falta columna 'Pais'."
assert 'Fecha' in df.columns, "Falta columna 'Fecha'."

# Fecha a numérico por si viene como texto
df['Fecha'] = pd.to_numeric(df['Fecha'], errors='coerce')

print("Dimensiones:", df.shape)
print("\nTipos de datos:\n", df.dtypes)
print("\nNulos por columna (top 10):\n", df.isna().sum().sort_values(ascending=False).head(10))

# Elige modo:
MODO = "promedio"     # "por_anio" o "promedio"
ANIO_OBJETIVO = 2008  # si None y MODO="por_anio", usa el más reciente

df_work = df.copy()

if MODO == "por_anio":
    if ANIO_OBJETIVO is None:
        ANIO_OBJETIVO = int(df_work['Fecha'].dropna().max())
        print(f"Usando año más reciente: {ANIO_OBJETIVO}")
    df_work = df_work[df_work['Fecha'] == ANIO_OBJETIVO].copy()
    assert len(df_work) > 0, f"No hay registros para {ANIO_OBJETIVO}"
else:
    # promedio por país de todas las numéricas (excluye Fecha)
    num_cols_all = df_work.select_dtypes(include=np.number).columns.drop('Fecha', errors='ignore')
    df_work = df_work.groupby('Pais', as_index=False)[list(num_cols_all)].mean()

print("Dimensiones de trabajo:", df_work.shape)
df_work.head()

# Numéricas candidatas (excluye 'Fecha')
cols_num = df_work.select_dtypes(include=np.number).columns.tolist()
cols_num = [c for c in cols_num if c.lower() != 'fecha']
assert len(cols_num) > 0, "No hay variables numéricas (aparte de 'Fecha')."

X = df_work[cols_num].copy()

# Imputación simple (mediana)
for c in cols_num:
    if X[c].isna().any():
        X[c] = X[c].fillna(X[c].median())

# Países para reportes
paises = df_work['Pais'].astype(str).values

#X_log=np.log1p(X)
#X_log = X_log.replace([np.inf,-np.inf], np.nan)
#X_log = X_log.fillna(X_log.mean())

#X_log, lambda = stats.boxcox(X)
X_log=np.arcsinh(X)
# Estandarización
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_log)

X_scaled.shape

"""
Se aplica **Análisis de Componentes Principales (PCA)** toma todas las **variables numéricas por país** y construye **nuevos ejes ortogonales** (PC1, PC2, …) que:
- Capturan **la mayor varianza posible** en las primeras componentes.
- **Reducen la dimensionalidad** y la **correlación** entre variables originales.
- Permiten **visualizar** y **clusterizar** (p. ej., con K-Means) en un espacio más compacto y estable.
"""

pca = PCA(random_state=SEED)
X_pca = pca.fit_transform(X_scaled)

exp_var = pca.explained_variance_ratio_
cum_exp_var = np.cumsum(exp_var)

fig = plt.figure(figsize=FIGSIZE)
plt.plot(range(1, len(exp_var)+1), exp_var, marker='o', label='Expl. individual',color='gray' )
plt.plot(range(1, len(exp_var)+1), cum_exp_var, marker='s', label='Expl. acumulada', color='blue')
plt.axhline(0.80, linestyle='--', linewidth=1)
plt.xlabel('Componente principal'); plt.ylabel('Proporción de varianza')
plt.title('PCA - Varianza explicada'); plt.legend()
plt.tight_layout(); plt.show()

# exp_var y cum_exp_var ya están definidos por tu bloque previo
cum_tbl = pd.DataFrame({
    "PC": np.arange(1, len(exp_var)+1),
    "Varianza_individual": np.round(exp_var, 4),
    "Varianza_acumulada": np.round(cum_exp_var, 4)
})

# Mostrar primeras 15 (ajusta si quieres más/menos)
display(cum_tbl.head(15))

# ¿Cuántos componentes se necesitan para 80%, 90% y 95%?
def n_for_thresh(cum, t):
    idx = np.argmax(cum >= t)
    return int(idx + 1) if cum[idx] >= t else None

n80 = n_for_thresh(cum_exp_var, 0.80)
n90 = n_for_thresh(cum_exp_var, 0.90)
n95 = n_for_thresh(cum_exp_var, 0.95)

print(f"\nComponentes para alcanzar ≥80%: {n80}")
print(f"Componentes para alcanzar ≥90%: {n90}")
print(f"Componentes para alcanzar ≥95%: {n95}")

# Sugerencia práctica para clustering: usa min(3, n80) si quieres pocas PCs estables
sugeridas_para_kmeans = min(3, n80 if n80 is not None else 3)
print(f"\nSugerencia rápida para K-Means: usar {sugeridas_para_kmeans} PCs (regla práctica).")

"""
Se muestran las cargas de los componentes principales

Las cargas son los **coeficientes** que indican cuánto **"peso" o "influencia"** tiene cada variable original en la construcción de un componente principal.


---
"""

pca_loadings = pd.DataFrame(
    pca.components_.T,
    index=cols_num,
    columns=[f'PC{i+1}' for i in range(pca.components_.shape[0])]
)


top_n = 10
# --- Display tables side-by-side ---
contrib1 = pca_loadings['PC1'].abs().sort_values(ascending=False).head(top_n).to_frame(name='|loading_PC1|')
contrib2 = pca_loadings['PC2'].abs().sort_values(ascending=False).head(top_n).to_frame(name='|loading_PC2|')
print(contrib1)
# Use display_html to show tables side by side
html_str = f'<div style="display: flex; justify-content: space-around;">{contrib1.to_html()}{contrib2.to_html()}</div>'
display(HTML(html_str))


# --- Display bar plots side-by-side ---
FIGSIZE = (15, 6)
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=FIGSIZE)

# Bar plot for PC1
contrib1.plot(kind='bar', ax=ax1, legend=False)
ax1.set_ylabel('|loading|')
ax1.set_title('Principales contribuciones en PC1')

# Bar plot for PC2
contrib2.plot(kind='bar', ax=ax2, legend=False)
ax2.set_ylabel('|loading|')
ax2.set_title('Principales contribuciones en PC2')

plt.tight_layout()
plt.savefig("bar_plots.png")

"""## Interpretación de Resultados


### **Análisis del Componente Principal 1 (PC1)**

Las variables que más pesan en este componente son:
- **Tasa_Mortalidad**
- **Indice_Crecimiento_Verde**
- **Indice_Gini** (desigualdad)
- **Tasa_Homicidios**
- **Habilidades_Estudiantes** y **Escolaridad**

**Interpretación**: PC1 parece ser un **índice de desarrollo y bienestar socioeconómico**. Las variables con más peso combinan aspectos de salud (mortalidad), seguridad (homicidios), desigualdad económica (Gini) y capital humano (educación). Un país con una puntuación alta en PC1 probablemente enfrente mayores desafíos en estas áreas, mientras que una puntuación baja podría indicar mejores condiciones sociales y económicas.

### **Análisis del Componente Principal 2 (PC2)**

Las variables con mayor carga en este eje son:
- **Empleo**
- **Desempleo_Largo_Plazo**
- **Agua_Dulce_Renovable**
- **Consumo_Energia_Renovable**
- **Polucion_Aire**

**Interpretación**: PC2 parece medir una dimensión que combina la **salud del mercado laboral con la sostenibilidad ambiental**. Por un lado, tenemos variables clave de empleo y desempleo. Por otro, indicadores de uso de recursos renovables y contaminación. Este eje podría separar a los países en función de su perfil económico-ambiental. Por ejemplo, podría diferenciar economías con mercados laborales robustos y una alta huella ambiental de aquellas con diferentes desafíos laborales pero un enfoque más sostenible.

## El Algoritmo K-Means

El objetivo de K-Means es agrupar los datos en $k$ clústeres, minimizando la **inercia**, que es la suma de las distancias al cuadrado de cada punto a su centroide (el centro de su clúster).



Para decidir cuántos clústeres ($k$) usar, se emplean principalmente dos métodos :

### 1. Método del Codo (Elbow Method)
Este método consiste en graficar la **inercia** (el valor de la fórmula WCSS de arriba) para diferentes valores de $k$. Se busca el punto en la gráfica donde la tasa de disminución de la inercia se reduce drásticamente, formando un "codo".


### 2. Índice de Silueta (Silhouette Score)
Mide qué tan bien está cada punto en su clúster. Compara la distancia de un punto con los demás en su propio clúster versus la distancia a los puntos del clúster más cercano.
"""

N_PC_FOR_CLUSTER = min(10, X_pca.shape[1])  # usar 2-3 PCs para clusterizar
Z = X_pca[:, :N_PC_FOR_CLUSTER]

Ks = list(range(2, min(11, Z.shape[0])))
inertias, silhouettes = [], []

for k in Ks:
    km = KMeans(n_clusters=k, n_init=20, random_state=SEED)
    labels_k = km.fit_predict(Z)
    inertias.append(km.inertia_)
    try:
        silhouettes.append(silhouette_score(Z, labels_k))
    except Exception:
        silhouettes.append(np.nan)

res_k = pd.DataFrame({"k": Ks, "inertia": inertias, "silhouette": silhouettes})
res_k

FIGSIZE = (12, 5)
fig, (ax1) = plt.subplots(1,  figsize=FIGSIZE)
fig, (ax2) = plt.subplots(1,  figsize=FIGSIZE)

# Codo
ax1.plot(res_k["k"], res_k["inertia"], marker='o', color='blue')
ax1.set_xlabel("k")
ax1.set_ylabel("Inercia")
ax1.set_title("Método del codo")
plt.tight_layout()

# Silueta
ax2.plot(res_k["k"], res_k["silhouette"], marker='s', color='blue')
ax2.set_xlabel("k")
ax2.set_ylabel("Índice de silueta")
ax2.set_title("Calidad por silueta")

plt.tight_layout()

K_FINAL = int(res_k.loc[res_k['silhouette'].idxmax(), 'k'])  # el mejor por silueta
print("k seleccionado:", K_FINAL)

km_final = KMeans(n_clusters=K_FINAL, n_init=50, random_state=SEED)
labels = km_final.fit_predict(Z)

# Proyección 2D para visualización
pca2 = PCA(n_components=2, random_state=SEED)
Z2 = pca2.fit_transform(X_scaled)

# --- PCA (2D) + KMeans con etiquetas, centroides y anti-solape ---
# Requiere: df_work, Z2, labels, K_FINAL, FIGSIZE definidos previamente

# (1) Instalar adjustText si hace falta (funciona en Colab)
try:
    from adjustText import adjust_text
except ImportError:
    !pip -q install adjustText
    from adjustText import adjust_text

paises = df_work['Pais'].astype(str).values

fig = plt.figure(figsize=FIGSIZE)
colors=['grey','blue']

# Dispersión por clúster
for c in range(K_FINAL):
    idx = (labels == c)
    plt.scatter(Z2[idx, 0], Z2[idx, 1], s=50, label=f'Cluster {c}', color=colors[c] )

# Centroides en el espacio Z2 (promedio por clúster)
centers2 = np.vstack([Z2[labels == c].mean(axis=0) for c in range(K_FINAL)])
plt.scatter(
    centers2[:, 0], centers2[:, 1],
    s=180, marker='X', color='blue', linewidth=1.2, alpha=0.95, label='Centroides'
)
# Etiquetas de centroides (C0, C1, ...)
for c, (x, y) in enumerate(centers2):
    plt.text(x, y, f"C{c}", fontsize=10, fontweight='bold', ha='center', va='center',color='blue')

# Etiquetas de países con anti-solape
texts = []
for i, name in enumerate(paises):
    texts.append(plt.text(Z2[i, 0], Z2[i, 1], name, fontsize=8, alpha=0.9))

# Ajuste para evitar solapamiento (puede tardar un poco si hay muchos puntos)
adjust_text(
    texts,
    expand_points=(1.2, 1.4),   # empuje desde los puntos
    expand_text=(1.05, 1.15),   # empuje entre textos
    arrowprops=dict(arrowstyle='-', lw=0.5, alpha=0.6)  # flechitas sutiles
)

plt.xlabel('PC1'); plt.ylabel('PC2'); plt.title('PCA (2D) + K-Means (etiquetas y centroides)')
plt.legend()
plt.tight_layout()
plt.show()

# Asegurarnos de tener una copia de trabajo alineada con 'labels'
df_work = df_work.copy()
df_work['Cluster'] = labels  # etiquetas del KMeans sobre Z

# 1) Listado de países por clúster (ordenados)
paises_por_cluster = (
    df_work[['Pais', 'Cluster']]
    .sort_values(['Cluster', 'Pais'])
    .groupby('Cluster')['Pais']
    .apply(list)
    .to_frame(name='Paises')
)
display(paises_por_cluster)

# 2) Valores medios por variable en escala original (no estandarizada)
#    Toma las columnas numéricas que usaste como features (cols_num)
medias_por_cluster = (
    df_work.groupby('Cluster')[cols_num]
    .mean()
    .round(3)
)
display(medias_por_cluster)

# 3) (Opcional) Centroides consistentes del KMeans en escala original
#    Reentrenamos KMeans en X_scaled y desescalamos los centroides
km_on_scaled = KMeans(n_clusters=K_FINAL, n_init=50, random_state=SEED).fit(X_scaled)
centroids_scaled = km_on_scaled.cluster_centers_
centroids_original = scaler.inverse_transform(centroids_scaled)

centroides_df = pd.DataFrame(centroids_original, columns=cols_num)
centroides_df.index.name = 'Cluster'
#display(centroides_df.round(3))

# 4) Exports
paises_por_cluster.to_csv('paises_por_cluster_listados.csv')
medias_por_cluster.to_csv('medias_por_cluster.csv')
centroides_df.to_csv('centroides_kmeans_en_original.csv', index=True)

print("Exportados: paises_por_cluster_listados.csv, medias_por_cluster.csv, centroides_kmeans_en_original.csv")

"""## DBSCAN: por qué y cómo leer sus resultados
**DBSCAN** (Density-Based Spatial Clustering of Applications with Noise) detecta **agrupaciones de alta densidad** y marca como **ruido (-1)** a observaciones aisladas. A diferencia de K-Means:


---

### Conceptos Fundamentales y Fórmulas
El algoritmo se basa en dos parámetros clave y la clasificación de cada punto en una de tres categorías.

- **`eps` ($\epsilon$)**: Define el **radio de la vecindad** alrededor de un punto. Es la distancia máxima que un punto puede tener para ser considerado "vecino" de otro. La fórmula para el conjunto de vecinos $N_{\epsilon}(p)$ de un punto $p$ es:
  $$N_{\epsilon}(p) = \{ q \in D \mid \text{dist}(p,q) \le \epsilon \}$$
  Donde $D$ es el conjunto de todos los datos y $\text{dist}(p,q)$ es la distancia entre los puntos $p$ y $q$.

- **`min_samples`**: Es el **número mínimo de puntos** que deben existir dentro de la vecindad $\epsilon$ de un punto para que esa zona se considere "densa".

"""

# --- Definir explícitamente 10 PCs para DBSCAN ---
N_PC_DBSCAN = min(10, X_pca.shape[1])  # 10 ya que con estos obtuvimos el 80% de la varianza explicada
Z_db = X_pca[:, :N_PC_DBSCAN]

# (Opcional) verificar varianza acumulada a 10 PCs
if len(cum_exp_var) >= 10:
    print(f"Varianza acumulada con 10 PCs: {cum_exp_var[9]:.3%}")
else:
    print(f"Solo hay {len(cum_exp_var)} PCs disponibles; varianza acumulada: {cum_exp_var[-1]:.3%}")

# Rango de min_samples a evaluar
MIN_SAMPLES_GRID = [3, 4, 5, 6, 8, 10]

def knee_eps_from_kdist(Z, ms):
    """eps candidato via 'codo' del k-distance plot."""
    n = Z.shape[0]
    # Asegurar un k válido: al menos 2 y menor a n
    ms_eff = max(2, min(ms, n - 1))
    nn = NearestNeighbors(n_neighbors=ms_eff).fit(Z)
    distances, _ = nn.kneighbors(Z)
    k_dist = np.sort(distances[:, -1])

    eps0, knee_idx = None, None
    try:
        kl = KneeLocator(
            x=np.arange(len(k_dist)), y=k_dist,
            curve="convex", direction="increasing"
        )
        knee_idx = kl.knee
        eps0 = float(k_dist[knee_idx]) if knee_idx is not None else None
    except Exception:
        eps0 = None

    if eps0 is None:
        eps0 = float(np.percentile(k_dist, 95))
        # índice aproximado del percentil (solo para dibujar)
        knee_idx = int(np.clip(round(0.95 * (len(k_dist) - 1)), 0, len(k_dist) - 1))
    return eps0, k_dist, knee_idx, ms_eff

def eval_dbscan(Z, eps_grid, ms):
    """Evalúa DBSCAN en rejilla de eps para un min_samples dado."""
    rows = []
    for eps in eps_grid:
        labels = DBSCAN(eps=float(eps), min_samples=int(ms)).fit_predict(Z)
        uniq = set(labels)
        n_clusters = len([u for u in uniq if u != -1])
        noise_frac = (labels == -1).mean()
        # silhouette solo si hay >=2 clústeres válidos y al menos 2 puntos válidos
        valid = labels != -1
        if n_clusters >= 2 and valid.sum() > 2:
            try:
                sil = silhouette_score(Z[valid], labels[valid])
            except Exception:
                sil = np.nan
        else:
            sil = np.nan
        rows.append({
            "min_samples": int(ms),
            "eps": float(eps),
            "n_clusters": int(n_clusters),
            "noise_frac": float(noise_frac),
            "silhouette": float(sil) if not np.isnan(sil) else np.nan
        })
    return pd.DataFrame(rows)

all_results = []
kdist_cache = {}  # {ms_eff: {"k_dist": array, "knee_idx": int, "eps0": float}}

for ms in MIN_SAMPLES_GRID:
    eps0, k_dist, knee_idx, ms_eff = knee_eps_from_kdist(Z_db, ms)
    # Rejilla fina alrededor del codo: ±20%
    eps_grid = np.linspace(eps0 * 0.8, eps0 * 1.2, 11)
    res_ms = eval_dbscan(Z_db, eps_grid, ms_eff)
    all_results.append(res_ms)
    kdist_cache[ms_eff] = {"k_dist": k_dist, "knee_idx": knee_idx, "eps0": eps0}

# Concatenar sin attrs (ya no hay arrays en attrs)
grid = pd.concat(all_results, ignore_index=True)

# Selección: mayor silhouette -> mayor n_clusters -> menor ruido -> menor min_samples
cands = grid.dropna(subset=["silhouette"])
if cands.empty:
    cands = grid.copy()

best = (cands.sort_values(
    by=["silhouette", "n_clusters", "noise_frac", "min_samples"],
    ascending=[False, False, True, True]
).iloc[0])

EPS_BEST = float(best["eps"])
MS_BEST = int(best["min_samples"])

print(f"DBSCAN óptimo -> eps={EPS_BEST:.4f}, min_samples={MS_BEST}, "
      f"silhouette={best.get('silhouette', np.nan):.3f}, "
      f"n_clusters={int(best['n_clusters'])}, ruido={best['noise_frac']:.2%}")

# Visual del k-distance de la mejor combinación
kdist_best = kdist_cache[MS_BEST]["k_dist"]
knee_idx_best = kdist_cache[MS_BEST]["knee_idx"]

fig = plt.figure(figsize=FIGSIZE)
plt.plot(kdist_best, label=f'k-distance (k=min_samples={MS_BEST})', color='grey')
if knee_idx_best is not None:
    plt.axvline(knee_idx_best, color='grey', linestyle='--', alpha=0.7, label='Codo')
    plt.axhline(kdist_best[knee_idx_best], color='blue', linestyle=':', alpha=0.7)
plt.axhline(EPS_BEST, color='blue', linestyle='-', alpha=0.8, label=f'eps seleccionado ≈ {EPS_BEST:.3f}')
plt.title(f'k-distance & eps seleccionado (min_samples={MS_BEST})')
plt.xlabel('Puntos ordenados'); plt.ylabel(f'Distancia al {MS_BEST}° vecino')
plt.legend(); plt.tight_layout(); plt.show()

# Entrenar DBSCAN final con la mejor combinación
db_final = DBSCAN(eps=EPS_BEST, min_samples=MS_BEST).fit(Z_db)
labels_db = db_final.labels_
uniq = np.unique(labels_db)
print("Etiquetas DBSCAN (incluye ruido -1):", uniq)

"""
# Selección Óptima de `eps` y `min_samples`

El algoritmo DBSCAN es muy potente, pero su rendimiento depende críticamente de una buena elección de sus dos parámetros: `eps` y `min_samples`. El código que has ejecutado no solo visualiza una recomendación, sino que realiza una **búsqueda sistemática y automatizada** para encontrar la mejor combinación.

---

## Interpretación del Gráfico `k-distance`

Este gráfico es la pieza central para estimar un buen valor de `eps` para un `min_samples` específico (.


- **Curva Naranja (`k-distance`)**: Representa la distancia de cada punto del dataset a su **3er vecino más cercano**. Las distancias están ordenadas de menor a mayor. La curva muestra cómo se distribuye la "densidad" en tus datos.
- **"Codo" (Línea Punteada Vertical)**: Es el punto de máxima curvatura de la línea naranja. El código lo detecta automáticamente usando la librería `kneed`. Este punto es teóricamente el umbral que mejor separa las zonas densas (a la izquierda del codo, con distancias bajas y estables) de las zonas dispersas o de ruido (a la derecha, donde las distancias crecen abruptamente). El valor de `eps` en este punto es una **excelente primera estimación**.
- **`eps` seleccionado (Línea Roja Horizontal)**: Este es el valor **final y optimizado** de `eps` que el código eligió.




En resumen, el código implementa una estrategia robusta:
1.  **Itera** sobre una lista de candidatos para `min_samples` (ej. [3, 4, 5...]).
2.  Para cada `min_samples`, **estima un `eps` inicial** usando el método del codo.
3.  **Refina la búsqueda de `eps`** en una rejilla pequeña alrededor de la estimación.
4.  **Evalúa** cada combinación (`eps`, `min_samples`) basándose en métricas objetivas (número de clústeres, ruido y, sobre todo, el **silhouette score**).
5.  Finalmente, **selecciona la combinación ganadora** que produjo los mejores resultados y la utiliza para generar la gráfica y el modelo final.

Este enfoque combina la intuición teórica del `k-distance plot` con una validación empírica para encontrar los parámetros óptimos de forma automática.
"""

# Asegurar proyección 2D (PC1-PC2) para graficar
try:
    Z2
except NameError:
    from sklearn.decomposition import PCA
    pca2 = PCA(n_components=2, random_state=SEED)
    Z2 = pca2.fit_transform(X_scaled)

# Instalar adjustText si hace falta
try:
    from adjustText import adjust_text
except ImportError:
    !pip -q install adjustText
    from adjustText import adjust_text

paises = df_work['Pais'].astype(str).values
uniq = np.unique(labels_db)
colors=['grey','blue','black']
fig = plt.figure(figsize=FIGSIZE)
for c in uniq:
    idx = (labels_db == c)
    label = "Ruido (-1)" if c == -1 else f"DBSCAN {c}"
    plt.scatter(Z2[idx, 0], Z2[idx, 1], s=50, label=label, color=colors[c])

# Etiquetar países incluyendo los de ruido (-1)
texts = []
for i, name in enumerate(paises):
    # Ahora incluimos todos los países, independientemente de su etiqueta de clúster
    texts.append(plt.text(Z2[i, 0], Z2[i, 1], name, fontsize=8, alpha=0.9))

if texts:
    adjust_text(
        texts,
        expand_points=(1.2, 1.4),
        expand_text=(1.05, 1.15),
        arrowprops=dict(arrowstyle='-', lw=0.5, alpha=0.6)
    )

plt.xlabel('PC1'); plt.ylabel('PC2'); plt.title('DBSCAN en PCs (2D) con etiquetas')
plt.legend(); plt.tight_layout(); plt.show()

# Silhouette sin ruido (si hay ≥2 clústeres válidos)
from sklearn.metrics import silhouette_score
valid = labels_db != -1
uniq_valid = np.unique(labels_db[valid])
if len(uniq_valid) >= 2 and valid.sum() > 2:
    sil_db = silhouette_score(Z_db[valid], labels_db[valid])
    print(f"Silhouette DBSCAN (sin ruido): {sil_db:.3f}")
else:
    print("Silhouette DBSCAN no aplicable (menos de 2 clústeres válidos sin ruido).")

# === Análisis de Clústeres DBSCAN: Países y Valores Medios ===

# Asegurarnos de tener una copia de trabajo
df_dbscan_work = df_work.copy()
# Usamos las etiquetas 'labels_db' generadas por el DBSCAN óptimo
df_dbscan_work['Cluster_DBSCAN'] = labels_db

# 1) Listado de países por clúster (incluyendo el grupo de Ruido -1)
paises_por_cluster_db = (
    df_dbscan_work[['Pais', 'Cluster_DBSCAN']]
    .sort_values(['Cluster_DBSCAN', 'Pais'])
    .groupby('Cluster_DBSCAN')['Pais']
    .apply(list)
    .to_frame(name='Paises')
)
print("--- Países por Clúster DBSCAN (el clúster -1 es Ruido) ---")
display(paises_por_cluster_db)

# 2) Valores medios por variable en escala original
# Esto nos da el "perfil" promedio de cada clúster
medias_por_cluster_db = (
    df_dbscan_work.groupby('Cluster_DBSCAN')[cols_num]
    .mean()
    .round(3)
)
print("\n--- Perfil Promedio por Clúster DBSCAN (en unidades originales) ---")
display(medias_por_cluster_db)

# Nota: DBSCAN no es un algoritmo basado en centroides como K-Means,
# por lo que no existe un atributo .cluster_centers_ para desescalar.
# La tabla de medias anterior es la forma correcta de interpretar el perfil de cada clúster.

# 3) Exports
paises_por_cluster_db.to_csv('dbscan_paises_por_cluster.csv')
medias_por_cluster_db.to_csv('dbscan_medias_por_cluster.csv')

print("\nExportados: dbscan_paises_por_cluster.csv, dbscan_medias_por_cluster.csv")

# Comparativo K-Means (10 PCs) vs DBSCAN ---
# comp asocia etiquetas por país
comp = pd.DataFrame({
    "Pais": df_work["Pais"].astype(str).values,
    "KMeans": labels,          # del entrenamiento K-Means (con 10 PCs si ya lo configuraste)
    "DBSCAN": labels_db        # del bloque 8A-OPT
}).sort_values(["KMeans", "DBSCAN", "Pais"]).reset_index(drop=True)

display(comp.head(40))
comp.to_csv("comparativo_kmeans_dbscan_por_pais.csv", index=False)
print("Exportado: comparativo_kmeans_dbscan_por_pais.csv")

# Crosstab excluyendo ruido de DBSCAN
mask_valid = comp["DBSCAN"] != -1
ct = pd.crosstab(comp.loc[mask_valid, "KMeans"], comp.loc[mask_valid, "DBSCAN"])
display(ct)

ct.to_csv("crosstab_kmeans_vs_dbscan.csv")
print("Exportado: crosstab_kmeans_vs_dbscan.csv")
