# -*- coding: utf-8 -*-
"""Alexis_base.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vwnhktnjj3qeyNx9KH7K0P7XfPNFaDbo
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('ggplot')
import seaborn as sns

# 1) LEER EL ARCHIVO CSV
data = pd.read_csv("Datos.csv")

# 2) RENOMBRAR COLUMNAS (DE PREFERENCIA EN ESPAÑOL PARA PONERLAS ASÍ EN LA TESIS)
nuevos_nombres = {
    'Country': 'Pais',
    'Year': 'Año',
    'CO2 Emissions (Mt CO2e)': 'Emisiones_CO2',
    'Age dependency ratio(%)': 'Ratio_Dependencia',
    'Trade (% of GDP)': 'Comercio_PIB',
    'GDP growth (%)': 'Crecimiento_PIB',
    'Coeficiente inverso de variacion': 'Coef_Inverso_Variacion',
    'HIRSCHMAN-HERFINDAHL INDEX (HHI)': 'Indice_HHI',
    ' Adjusted net saving (%)': 'Ahorro_Neto_Ajustado',
    'Goverment Debt (%)': 'Deuda_Gobierno',
    'Air pollution (%)': 'Polucion_Aire',
    'Intensidad de CO2 (kg CO2 per)': 'Intensidad_CO2',
    'Renewable energy consumption (%)': 'Consumo_Energia_Renovable',
    'Energy intensity (MJ)': 'Intensidad_Energetica',
    'Renewable freshwater (cubic meters)': 'Agua_Dulce_Renovable',
    'Natural resources rents (%)': 'Renta_Recursos_Naturales',
    'Water productivity ($ GDP por metro cubico)': 'Productividad_Agua',
    'Acces electricity (%)': 'Acceso_Electricidad',
    'Using drinking water (%)': 'Consumo_Agua_Potable',
    'Employment (%)': 'Empleo',
    'indice de Gini': 'Indice_Gini',
    'Mortaly rate (%)': 'Tasa_Mortalidad',
    'Life expentacy (years)': 'Esperanza_Vida',
    'Poverty gap (%)': 'Brecha_Pobreza',
    'Primary completion (%)': 'Finalizacion_Primaria',
    'Sanitation services (%)': 'Servicios_Saneamiento',
    'School  enrollment, gender parity index': 'Paridad_Genero_Educacion',
    'LABOR FORCE PARTICIPATION  (% POINTS)': 'Participacion_Laboral',
    'Years scholling': 'Años_Escolaridad',
    'Indice de crecimiento verde': 'Indice_Crecimiento_Verde',
    'Students abilities': 'Habilidades_Estudiantes',
    'Educational attainment (%)': 'Logros_Educativos',
    'Dwellings without basic facilities (%)': 'Viviendas_Sin_Servicios',
    'Housing expenditure (%)': 'Gastos_Vivienda',
    'Adjusted net national ($)': 'Ajuste_Neto_Nacional',
    'Household net wealth (%)': 'Riqueza_Neta_Hogares',
    'Unemployed long term (%)': 'Desempleo_Largo_Plazo',
    'Personal earning ($)': 'Ingresos_Personales',
    'Quality of support network (%)': 'Calidad_Red_Apoyo',
    'Stakeholder engagement': 'Compromiso_Partes_Interesadas',
    'Life satisfaction': 'Satisfaccion_Vida',
    'Homicide rate (por cada 100,000)': 'Tasa_Homicidios',
    'Time to leisure ande personal care': 'Tiempo_Ocio_Cuidado_Personal'
}
data.rename(columns=nuevos_nombres, inplace=True)
data

# 3) ORDENAR POR 'Pais' Y 'Año'
data.sort_values(by=['Pais', 'Año'], inplace=True)
data

# 4) LISTAR LAS COLUMNAS NUMÉRICAS
numeric_cols = data.select_dtypes(include=[np.number]).columns
numeric_cols

# 5) AGRUPAR POR 'Pais'
grupos = data.groupby('Pais')
resultados = []  # aquí iremos guardando cada grupo procesado

for pais, df_pais in grupos:
    # df_pais contiene solo las filas de un país

    # a) Ordenar dentro del país por 'Año'
    df_pais = df_pais.sort_values(by='Año')

    # b) Interpolar cada columna numérica
    for col in numeric_cols:
        df_pais[col] = df_pais[col].interpolate(method='linear', limit_direction='both')

    # c) Rellenar valores faltantes restantes con la mediana local (del mismo país)
    for col in numeric_cols:
        # Si queda NaN, lo llenamos con la mediana de ese grupo
        df_pais[col].fillna(df_pais[col].median(), inplace=True)

    # Agregar el DataFrame del país ya limpio a la lista
    resultados.append(df_pais)

# 6) CONCATENAR TODOS LOS GRUPOS
data_limpia = pd.concat(resultados, ignore_index=True)
data_limpia

# 7) VERIFICAR SI QUEDAN VALORES FALTANTES
print("¿Hay valores NA en el dataset?:", data_limpia.isna().any().any())
print("Valores nulos por columna:\n", data_limpia.isna().sum())

# Eliminar las columnas que aún contienen valores faltantes
data_limpia = data_limpia.dropna(axis=1)

# Confirmar la eliminación
print("Listado de columnas tras eliminar variables con NA:")
data_limpia.columns

# 8) LISTAR PAÍSES
print("Listado de países en el dataset:")
print(data_limpia['Pais'].unique())

# 9) ANÁLISIS DE CORRELACIÓN (para las columnas numéricas)
# Recalcular las columnas numéricas del DataFrame limpio
numeric_cols = data_limpia.select_dtypes(include=[np.number]).columns
correlation = data_limpia[numeric_cols].corr()
print("Correlación entre variables numéricas:")
correlation

# 10) IDENTIFICAR LAS VARIABLES CON MAYOR CORRELACIÓN
high_corr = correlation.abs().unstack().sort_values(kind="quicksort", ascending=False)

# Eliminar la autocorrelación (corr de una variable consigo misma)
high_corr = high_corr[high_corr != 1]
print("Pares de variables con alta correlación:")
print(high_corr.head(10))

# Crear una máscara que seleccione solo el triángulo superior (sin la diagonal)
mask = np.triu(np.ones_like(correlation, dtype=bool), k=1)
unique_corr = correlation.where(mask).stack().abs().sort_values(ascending=False)

print("Pares de variables con alta correlación (sin duplicados):")
print(unique_corr.head(10))

# 11) GRAFICAR BOX PLOTS DE ALGUNAS VARIABLES DE INTERÉS
# (aquí pones las variables específicas que te interesan, por ejemplo)
variables_de_interes = ['Emisiones_CO2', 'Crecimiento_PIB']  # Ajusta según tu dataset
fig, axs = plt.subplots(1, len(variables_de_interes), figsize=(12, 6))

# Rotación de etiquetas para que se lean los nombres de países si son muchos
for i, var in enumerate(variables_de_interes):
    sns.boxplot(x='Pais', y=var, data=data_limpia, ax=axs[i])
    axs[i].set_xticklabels(axs[i].get_xticklabels(), rotation=90)
    axs[i].set_title(f'Boxplot de {var} por País')

plt.tight_layout()
plt.show()

# 12) ESTADÍSTICAS DESCRIPTIVAS
print("Estadísticas descriptivas del dataset:")
data_limpia.describe()

# 13) HISTOGRAMAS DE LAS VARIABLES NUMÉRICAS
sns.set(style="whitegrid", palette="viridis")
ax = data_limpia[numeric_cols].hist(bins=15, figsize=(15, 10))
plt.suptitle('Histogramas de Variables Numéricas', fontsize=16)
plt.tight_layout(rect=[0, 0, 1, 0.95])
plt.show()

# 14) GUARDAR EL CSV FINAL
data_limpia.to_csv('final.csv', index=False)
